<?php
$fields = array(
    "agriculture",
    "architecture",
    "art",
    "aviation",
    "banking",
    "biology",
    "computing",
    "culture",
    "economics",
    "education",
    "finance",
    "food",
    "history",
    "immigration and refugees",
    "insurance",
    "journals",
    "law",
    "literature",
    "management",
    "marketing",
    "mathematics",
    "medicine",
    "metallurgy",
    "physics",
    "police",
    "politics",
    "science",
    "sport",
    "transport",
    "translation",
);

?>
