<?php
$countries = [
array("Country"=>"Andorra", "Id"=>"AD"),
array("Country"=>"United Arab Emirates", "Id"=>"AE"),
array("Country"=>"Afghanistan", "Id"=>"AF"),
array("Country"=>"Antigua and Barbuda", "Id"=>"AG"),
array("Country"=>"Anguilla", "Id"=>"AI"),
array("Country"=>"Albania", "Id"=>"AL"),
array("Country"=>"Armenia", "Id"=>"AM"),
array("Country"=>"Netherlands Antilles", "Id"=>"AN"),
array("Country"=>"Angola", "Id"=>"AO"),
array("Country"=>"Asia/Pacific Region", "Id"=>"AP"),
array("Country"=>"Antarctica", "Id"=>"AQ"),
array("Country"=>"Argentina", "Id"=>"AR"),
array("Country"=>"American Samoa", "Id"=>"AS"),
array("Country"=>"Austria", "Id"=>"AT"),
array("Country"=>"Australia", "Id"=>"AU"),
array("Country"=>"Aruba", "Id"=>"AW"),
array("Country"=>"Aland Islands", "Id"=>"AX"),
array("Country"=>"Azerbaijan", "Id"=>"AZ"),
array("Country"=>"Bosnia and Herzegovina", "Id"=>"BA"),
array("Country"=>"Barbados", "Id"=>"BB"),
array("Country"=>"Bangladesh", "Id"=>"BD"),
array("Country"=>"Belgium", "Id"=>"BE"),
array("Country"=>"Burkina Faso", "Id"=>"BF"),
array("Country"=>"Bulgaria", "Id"=>"BG"),
array("Country"=>"Bahrain", "Id"=>"BH"),
array("Country"=>"Burundi", "Id"=>"BI"),
array("Country"=>"Benin", "Id"=>"BJ"),
array("Country"=>"Bermuda", "Id"=>"BM"),
array("Country"=>"Brunei Darussalam", "Id"=>"BN"),
array("Country"=>"Bolivia", "Id"=>"BO"),
array("Country"=>"Brazil", "Id"=>"BR"),
array("Country"=>"Bahamas", "Id"=>"BS"),
array("Country"=>"Bhutan", "Id"=>"BT"),
array("Country"=>"Bouvet Island", "Id"=>"BV"),
array("Country"=>"Botswana", "Id"=>"BW"),
array("Country"=>"Belarus", "Id"=>"BY"),
array("Country"=>"Belize", "Id"=>"BZ"),
array("Country"=>"Canada", "Id"=>"CA"),
array("Country"=>"Cocos (Keeling) Islands", "Id"=>"CC"),
array("Country"=>"Congo", "Id"=>"CD"),
array("Country"=>"Central African Republic", "Id"=>"CF"),
array("Country"=>"Congo", "Id"=>"CG"),
array("Country"=>"Switzerland", "Id"=>"CH"),
array("Country"=>"Cote d'Ivoire", "Id"=>"CI"),
array("Country"=>"Cook Islands", "Id"=>"CK"),
array("Country"=>"Chile", "Id"=>"CL"),
array("Country"=>"Cameroon", "Id"=>"CM"),
array("Country"=>"China", "Id"=>"CN"),
array("Country"=>"Colombia", "Id"=>"CO"),
array("Country"=>"Costa Rica", "Id"=>"CR"),
array("Country"=>"Cuba", "Id"=>"CU"),
array("Country"=>"Cape Verde", "Id"=>"CV"),
array("Country"=>"Christmas Island", "Id"=>"CX"),
array("Country"=>"Cyprus", "Id"=>"CY"),
array("Country"=>"Czech Republic", "Id"=>"CZ"),
array("Country"=>"Germany", "Id"=>"DE"),
array("Country"=>"Djibouti", "Id"=>"DJ"),
array("Country"=>"Denmark", "Id"=>"DK"),
array("Country"=>"Dominica", "Id"=>"DM"),
array("Country"=>"Dominican Republic", "Id"=>"DO"),
array("Country"=>"Algeria", "Id"=>"DZ"),
array("Country"=>"Ecuador", "Id"=>"EC"),
array("Country"=>"Estonia", "Id"=>"EE"),
array("Country"=>"Egypt", "Id"=>"EG"),
array("Country"=>"Western Sahara", "Id"=>"EH"),
array("Country"=>"Eritrea", "Id"=>"ER"),
array("Country"=>"Spain", "Id"=>"ES"),
array("Country"=>"Ethiopia", "Id"=>"ET"),
array("Country"=>"Europe", "Id"=>"EU"),
array("Country"=>"Finland", "Id"=>"FI"),
array("Country"=>"Fiji", "Id"=>"FJ"),
array("Country"=>"Falkland Islands (Malvinas)", "Id"=>"FK"),
array("Country"=>"Micronesia", "Id"=>"FM"),
array("Country"=>"Faroe Islands", "Id"=>"FO"),
array("Country"=>"France", "Id"=>"FR"),
array("Country"=>"Gabon", "Id"=>"GA"),
array("Country"=>"United Kingdom", "Id"=>"GB"),
array("Country"=>"Grenada", "Id"=>"GD"),
array("Country"=>"Georgia", "Id"=>"GE"),
array("Country"=>"French Guiana", "Id"=>"GF"),
array("Country"=>"Guernsey", "Id"=>"GG"),
array("Country"=>"Ghana", "Id"=>"GH"),
array("Country"=>"Gibraltar", "Id"=>"GI"),
array("Country"=>"Greenland", "Id"=>"GL"),
array("Country"=>"Gambia", "Id"=>"GM"),
array("Country"=>"Guinea", "Id"=>"GN"),
array("Country"=>"Guadeloupe", "Id"=>"GP"),
array("Country"=>"Equatorial Guinea", "Id"=>"GQ"),
array("Country"=>"Greece", "Id"=>"GR"),
array("Country"=>"South Georgia and the South Sandwich Islands", "Id"=>"GS"),
array("Country"=>"Guatemala", "Id"=>"GT"),
array("Country"=>"Guam", "Id"=>"GU"),
array("Country"=>"Guinea-Bissau", "Id"=>"GW"),
array("Country"=>"Guyana", "Id"=>"GY"),
array("Country"=>"Hong Kong", "Id"=>"HK"),
array("Country"=>"Heard Island and McDonald Islands", "Id"=>"HM"),
array("Country"=>"Honduras", "Id"=>"HN"),
array("Country"=>"Croatia", "Id"=>"HR"),
array("Country"=>"Haiti", "Id"=>"HT"),
array("Country"=>"Hungary", "Id"=>"HU"),
array("Country"=>"Indonesia", "Id"=>"ID"),
array("Country"=>"Ireland", "Id"=>"IE"),
array("Country"=>"Israel", "Id"=>"IL"),
array("Country"=>"Isle of Man", "Id"=>"IM"),
array("Country"=>"India", "Id"=>"IN"),
array("Country"=>"British Indian Ocean Territory", "Id"=>"IO"),
array("Country"=>"Iraq", "Id"=>"IQ"),
array("Country"=>"Iran", "Id"=>"IR"),
array("Country"=>"Iceland", "Id"=>"IS"),
array("Country"=>"Italy", "Id"=>"IT"),
array("Country"=>"Jersey", "Id"=>"JE"),
array("Country"=>"Jamaica", "Id"=>"JM"),
array("Country"=>"Jordan", "Id"=>"JO"),
array("Country"=>"Japan", "Id"=>"JP"),
array("Country"=>"Kenya", "Id"=>"KE"),
array("Country"=>"Kyrgyzstan", "Id"=>"KG"),
array("Country"=>"Cambodia", "Id"=>"KH"),
array("Country"=>"Kiribati", "Id"=>"KI"),
array("Country"=>"Comoros", "Id"=>"KM"),
array("Country"=>"Saint Kitts and Nevis", "Id"=>"KN"),
array("Country"=>"Korea", "Id"=>"KP"),
array("Country"=>"Korea", "Id"=>"KR"),
array("Country"=>"Kuwait", "Id"=>"KW"),
array("Country"=>"Cayman Islands", "Id"=>"KY"),
array("Country"=>"Kazakhstan", "Id"=>"KZ"),
array("Country"=>"Lao People's Democratic Republic", "Id"=>"LA"),
array("Country"=>"Lebanon", "Id"=>"LB"),
array("Country"=>"Saint Lucia", "Id"=>"LC"),
array("Country"=>"Liechtenstein", "Id"=>"LI"),
array("Country"=>"Sri Lanka", "Id"=>"LK"),
array("Country"=>"Liberia", "Id"=>"LR"),
array("Country"=>"Lesotho", "Id"=>"LS"),
array("Country"=>"Lithuania", "Id"=>"LT"),
array("Country"=>"Luxembourg", "Id"=>"LU"),
array("Country"=>"Latvia", "Id"=>"LV"),
array("Country"=>"Libyan Arab Jamahiriya", "Id"=>"LY"),
array("Country"=>"Morocco", "Id"=>"MA"),
array("Country"=>"Monaco", "Id"=>"MC"),
array("Country"=>"Moldova", "Id"=>"MD"),
array("Country"=>"Montenegro", "Id"=>"ME"),
array("Country"=>"Madagascar", "Id"=>"MG"),
array("Country"=>"Marshall Islands", "Id"=>"MH"),
array("Country"=>"Macedonia", "Id"=>"MK"),
array("Country"=>"Mali", "Id"=>"ML"),
array("Country"=>"Myanmar", "Id"=>"MM"),
array("Country"=>"Mongolia", "Id"=>"MN"),
array("Country"=>"Macao", "Id"=>"MO"),
array("Country"=>"Northern Mariana Islands", "Id"=>"MP"),
array("Country"=>"Martinique", "Id"=>"MQ"),
array("Country"=>"Mauritania", "Id"=>"MR"),
array("Country"=>"Montserrat", "Id"=>"MS"),
array("Country"=>"Malta", "Id"=>"MT"),
array("Country"=>"Mauritius", "Id"=>"MU"),
array("Country"=>"Maldives", "Id"=>"MV"),
array("Country"=>"Malawi", "Id"=>"MW"),
array("Country"=>"Mexico", "Id"=>"MX"),
array("Country"=>"Malaysia", "Id"=>"MY"),
array("Country"=>"Mozambique", "Id"=>"MZ"),
array("Country"=>"Namibia", "Id"=>"NA"),
array("Country"=>"New Caledonia", "Id"=>"NC"),
array("Country"=>"Niger", "Id"=>"NE"),
array("Country"=>"Norfolk Island", "Id"=>"NF"),
array("Country"=>"Nigeria", "Id"=>"NG"),
array("Country"=>"Nicaragua", "Id"=>"NI"),
array("Country"=>"Netherlands", "Id"=>"NL"),
array("Country"=>"Norway", "Id"=>"NO"),
array("Country"=>"Nepal", "Id"=>"NP"),
array("Country"=>"Nauru", "Id"=>"NR"),
array("Country"=>"Niue", "Id"=>"NU"),
array("Country"=>"New Zealand", "Id"=>"NZ"),
array("Country"=>"Oman", "Id"=>"OM"),
array("Country"=>"Panama", "Id"=>"PA"),
array("Country"=>"Peru", "Id"=>"PE"),
array("Country"=>"French Polynesia", "Id"=>"PF"),
array("Country"=>"Papua New Guinea", "Id"=>"PG"),
array("Country"=>"Philippines", "Id"=>"PH"),
array("Country"=>"Pakistan", "Id"=>"PK"),
array("Country"=>"Poland", "Id"=>"PL"),
array("Country"=>"Saint Pierre and Miquelon", "Id"=>"PM"),
array("Country"=>"Pitcairn", "Id"=>"PN"),
array("Country"=>"Puerto Rico", "Id"=>"PR"),
array("Country"=>"Palestinian Territory", "Id"=>"PS"),
array("Country"=>"Portugal", "Id"=>"PT"),
array("Country"=>"Palau", "Id"=>"PW"),
array("Country"=>"Paraguay", "Id"=>"PY"),
array("Country"=>"Qatar", "Id"=>"QA"),
array("Country"=>"Reunion", "Id"=>"RE"),
array("Country"=>"Romania", "Id"=>"RO"),
array("Country"=>"Serbia", "Id"=>"RS"),
array("Country"=>"Russian Federation", "Id"=>"RU"),
array("Country"=>"Rwanda", "Id"=>"RW"),
array("Country"=>"Saudi Arabia", "Id"=>"SA"),
array("Country"=>"Solomon Islands", "Id"=>"SB"),
array("Country"=>"Seychelles", "Id"=>"SC"),
array("Country"=>"Sudan", "Id"=>"SD"),
array("Country"=>"Sweden", "Id"=>"SE"),
array("Country"=>"Singapore", "Id"=>"SG"),
array("Country"=>"Saint Helena", "Id"=>"SH"),
array("Country"=>"Slovenia", "Id"=>"SI"),
array("Country"=>"Svalbard and Jan Mayen", "Id"=>"SJ"),
array("Country"=>"Slovakia", "Id"=>"SK"),
array("Country"=>"Sierra Leone", "Id"=>"SL"),
array("Country"=>"San Marino", "Id"=>"SM"),
array("Country"=>"Senegal", "Id"=>"SN"),
array("Country"=>"Somalia", "Id"=>"SO"),
array("Country"=>"SuriCountry", "Id"=>"SR"),
array("Country"=>"Sao Tome and Principe", "Id"=>"ST"),
array("Country"=>"El Salvador", "Id"=>"SV"),
array("Country"=>"Syrian Arab Republic", "Id"=>"SY"),
array("Country"=>"Swaziland", "Id"=>"SZ"),
array("Country"=>"Turks and Caicos Islands", "Id"=>"TC"),
array("Country"=>"Chad", "Id"=>"TD"),
array("Country"=>"French Southern Territories", "Id"=>"TF"),
array("Country"=>"Togo", "Id"=>"TG"),
array("Country"=>"Thailand", "Id"=>"TH"),
array("Country"=>"Tajikistan", "Id"=>"TJ"),
array("Country"=>"Tokelau", "Id"=>"TK"),
array("Country"=>"Timor-Leste", "Id"=>"TL"),
array("Country"=>"Turkmenistan", "Id"=>"TM"),
array("Country"=>"Tunisia", "Id"=>"TN"),
array("Country"=>"Tonga", "Id"=>"TO"),
array("Country"=>"Turkey", "Id"=>"TR"),
array("Country"=>"Trinidad and Tobago", "Id"=>"TT"),
array("Country"=>"Tuvalu", "Id"=>"TV"),
array("Country"=>"Taiwan", "Id"=>"TW"),
array("Country"=>"Tanzania", "Id"=>"TZ"),
array("Country"=>"Ukraine", "Id"=>"UA"),
array("Country"=>"Uganda", "Id"=>"UG"),
array("Country"=>"United States Minor Outlying Islands", "Id"=>"UM"),
array("Country"=>"United States", "Id"=>"US"),
array("Country"=>"Uruguay", "Id"=>"UY"),
array("Country"=>"Uzbekistan", "Id"=>"UZ"),
array("Country"=>"Holy See (Vatican City State)", "Id"=>"VA"),
array("Country"=>"Saint Vincent and the Grenadines", "Id"=>"VC"),
array("Country"=>"Venezuela", "Id"=>"VE"),
array("Country"=>"Virgin Islands", "Id"=>"VG"),
array("Country"=>"Virgin Islands", "Id"=>"VI"),
array("Country"=>"Vietnam", "Id"=>"VN"),
array("Country"=>"Vanuatu", "Id"=>"VU"),
array("Country"=>"Wallis and Futuna", "Id"=>"WF"),
array("Country"=>"Samoa", "Id"=>"WS"),
array("Country"=>"Yemen", "Id"=>"YE"),
array("Country"=>"Mayotte", "Id"=>"YT"),
array("Country"=>"South Africa", "Id"=>"ZA"),
array("Country"=>"Zambia", "Id"=>"ZM"),
array("Country"=>"Zimbabwe", "Id"=>"ZW")
];

exit(json_encode($countries));
?>
